# Generated by Django 4.1.7 on 2023-02-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=True, max_digits=10)),
                ('image1', models.ImageField(blank=True, upload_to='product')),
                ('image2', models.ImageField(blank=True, upload_to='product')),
                ('image3', models.ImageField(blank=True, upload_to='product')),
                ('image4', models.ImageField(blank=True, upload_to='product')),
                ('image5', models.ImageField(blank=True, upload_to='product')),
                ('image6', models.ImageField(blank=True, upload_to='product')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ('name',),
            },
        ),
    ]
