# Generated by Django 4.1.7 on 2023-02-27 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=100, null=True)),
                ('carmodel', models.CharField(max_length=100, null=True)),
                ('Contact', models.BigIntegerField(default=0)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('testdate', models.DateField(null=True)),
                ('testtime', models.TimeField(blank=True, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='carapp.customer')),
            ],
            options={
                'verbose_name': 'test_drive',
                'verbose_name_plural': 'test_drive',
                'ordering': ('carmodel',),
            },
        ),
    ]
